# Site
repository: 14likhit/14likhit.github.io
favicon: images/mobile.png

darkmode: true

# Personal info
name: Likhit Undkat
title: Android Developer
email: 14likhit@gmail.com
website: 14likhit.github.io

# Social links
twitter_username: 14likhit
github_username:  14likhit
# dribbble_username:
# facebook_username:
# flickr_username:
# instagram_username: jameswgrant
linkedin_username: likhit-unadkat-263006a4
# pinterest_username:
# youtube_username:
# googleplus_username:

# About Section
# about_title: About Me
about_profile_image: images/whats_likhit.jpeg
about_content: |
  Hi, my name is Likhit Unadkat, I'm an android app developer with over 4 years experience, based in the Bangalore.
  I am currently working as Android Engineer at [Aktivolabs](https://www.aktivolabs.com/) (Aktivo is your daily companion in making the right lifestyle choices. A good Aktivo Score® is your scientific guide to living a long and healthy life.).

  I enjoy making clean and interactive UI that is quick and easy to use whilst also giving users an enjoyable experience.
  I have worked with a range of different languages and frameworks and I am always looking for opportunities to work
  with something new. The things that I currently have the most experience working with are:
  <mark>Android</mark>,
  <mark>Kotlin</mark>,
  <mark>Firebase</mark>,
  <mark>Java</mark>,
  <mark>Python</mark>,
  <mark>Django</mark>,
  <mark>PostgreSQL</mark>,
  <mark>git</mark>.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: When I'm Not Programming
more_content: |
  When I'm not at my desk I am very active traveller and spend most of my time outdoors. I love running and cycling. Just fininshed one half-marathon.
  Also I like cooking, writing poem and reading. Since my time in Engineering I have become a very keen cook and believe
  cooking helps me learn experimentation. In 2019 I competed Jagriti Yatra, a unique 15 day train journey which covers 
  almost 8000km across India.

  Writing poems have help me expand my creativity. I like to write poems in Hindi. 
  I like to showcase my work on my instagram, if you would like to take a look -
  [likhit](https://www.instagram.com/14likhit/).

  Finally during the rest of my free time you will either find me reading books or watching documentaries.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
