# Site
repository: 14likhit/14likhit.github.io
favicon: images/mobile.png

darkmode: true

# Personal info
name: Likhit Undkat
title: Android Developer
email: 14likhit@gmail.com
website: 14likhit.github.io

# Social links
twitter_username: 14likhit
github_username:  14likhit
# dribbble_username:
# facebook_username:
# flickr_username:
# instagram_username: jameswgrant
linkedin_username: likhit-unadkat-263006a4
# pinterest_username:
# youtube_username:
# googleplus_username:

# About Section
# about_title: About Me
about_profile_image: images/whats_likhit.jpeg
about_content: |
  Hi, my name is Likhit Unadkat, I'm an Android app developer with over 7 years of experience, based in the Bangalore.I’m passionate about creating seamless, high-quality digital experiences that delight users and drive impact.
  
  I am currently working as Lead Android Engineer at [Semaai](https://www.semaai.com/en) (Semmai is empowering Indonesian farmers to improve their livelihoods.). My role here extends beyond coding; I closely align with product teams to ensure we deliver meaningful, user-centered solutions.

  - **Tech & Product Expertise**: Hands-on experience in end-to-end product development, from ideation to release, with a strong product-oriented mindset gained as a founding engineer.  
  - **Leadership**: Proven ability to build and lead high-performing teams, fostering innovation and ownership.  
  - **Technical Proficiency**: Expertise in Android, Kotlin, Jetpack Compose, Java, Firebase, Python, Django, PostgreSQL, and Git.  
  - **Startup Enthusiasm**: Passionate about startups, excelling in fast-paced environments with a focus on product-market fit, user engagement, and scalability.  
  - **Design Philosophy**: Committed to creating clean, intuitive, and interactive UIs that ensure exceptional user experiences.  
  - **Beyond Code**: Lifelong learner, tech enthusiast, and mentor, actively contributing to the tech community.  

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: When I'm Not Programming
more_content: |
  When I’m not at my desk, I’m an active traveler who loves spending time outdoors. I enjoy running and cycling and have completed multiple half-marathons.

  I’m also passionate about cooking, which I’ve embraced since my engineering days. Cooking not only satisfies my love for food but also teaches me the art of experimentation. As a self-proclaimed foodie, I’m always on the lookout for new food joints to explore and savor different cuisines.

  In 2019, I had the incredible opportunity to participate in Jagriti Yatra, a unique 15-day train journey that covers almost 8,000 km across India, igniting my love for adventure and exploration.

  Writing poems have help me expand my creativity. I like to write poems in Hindi. 
  I like to showcase my work on my instagram, if you would like to take a look -
  [likhit](https://www.instagram.com/14likhit/).

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
